sudo: false
addons:
  apt:
    packages:
    - libgd2-xpm-dev
language: perl
perl:
  - "5.16"
before_install:
  - cpanm --quiet --notest Alien::Tidyp
before_script:
  - mysql -e 'create database npgt;'
env:
  - TEST_AUTHOR=1 TZ=Europe/London
